### ISSUE TITLE
Conflicting mods (Maybe?)

### ISSUE THREAD

**Issue by BlackburnB2** [Urban-Coalition/ArcCW_UD#21]
There's an addon called 'Dynamic Weapon Reverb' - makes reverbs for guns when you're inside, outside, and under water.

When I used the said addon with **this** addon, the reverb works whenever I hipfire. But, whenever I use ironsights, the reverb doesn't work - only when in ironsights.

**Comment by Taskmer** [comment]
Has been fixed, however shotguns seem to be incredibly loud for some reason.

**Comment by TheOnly8Z** [comment]
> Has been fixed, however shotguns seem to be incredibly loud for some reason.

Likely because ArcCW calls FireBullets once for each pellet.

**Comment by SpiffyJUNIOR** [comment]
> Has been fixed, however shotguns seem to be incredibly loud for some reason.
fixed by e330c7dcd9f9588d2f8e1a577f1ed5b03ca034b3, can you guys close this issue

**Comment by SpiffyJUNIOR** [comment]
> Has been fixed, however shotguns seem to be incredibly loud for some reason.

 fixed by e330c7dcd9f9588d2f8e1a577f1ed5b03ca034b3, can you guys close this issue
